// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error(
    "Missing Supabase environment variables. Please set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY."
  );
}

const DEFAULT_SUPABASE_REQUEST_TIMEOUT_MS = 20000;
const STORAGE_UPLOAD_TIMEOUT_MS = 90000;
let requestSeq = 0;

const isDebugSupabase = () => {
  try {
    return localStorage.getItem("debug_supabase") === "1";
  } catch {
    return false;
  }
};

const fetchWithTimeout: typeof fetch = async (input, init) => {
  const attemptFetch = async () => {
    const requestId = ++requestSeq;
    const requestUrl = typeof input === "string" ? input : input.url;
    const requestMethod = (init?.method ?? "GET").toUpperCase();
    const isStorageUpload =
      requestMethod === "POST" && requestUrl.includes("/storage/v1/object/");
    const timeoutMs = isStorageUpload
      ? STORAGE_UPLOAD_TIMEOUT_MS
      : DEFAULT_SUPABASE_REQUEST_TIMEOUT_MS;
    const startedAt = performance.now();
    const debug = isDebugSupabase();

    if (debug) {
      console.log("[SB_REQ_START]", {
        requestId,
        requestMethod,
        requestUrl,
        timeoutMs,
        visibility: document.visibilityState,
        online: navigator.onLine,
      });
    }

    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), timeoutMs);

    if (init?.signal) {
      if (init.signal.aborted) {
        clearTimeout(timeoutId);
        throw new DOMException("Aborted", "AbortError");
      }
      init.signal.addEventListener("abort", () => controller.abort(), { once: true });
    }

    try {
      const response = await fetch(input, { ...init, signal: controller.signal });
      if (debug) {
        console.log("[SB_REQ_END]", {
          requestId,
          status: response.status,
          durationMs: Math.round(performance.now() - startedAt),
          requestMethod,
          requestUrl,
        });
      }
      return response;
    } catch (error) {
      const isTimeoutAbort =
        error instanceof DOMException && error.name === "AbortError";

      if (isTimeoutAbort) {
        if (debug) {
          console.error("[SB_REQ_TIMEOUT]", {
            requestId,
            durationMs: Math.round(performance.now() - startedAt),
            requestMethod,
            requestUrl,
            timeoutMs,
          });
        }
        throw new Error(`[NETWORK_TIMEOUT] Supabase request quá ${timeoutMs / 1000}s`);
      }
      if (debug) {
        console.error("[SB_REQ_ERROR]", {
          requestId,
          durationMs: Math.round(performance.now() - startedAt),
          requestMethod,
          requestUrl,
          error,
        });
      }
      throw error;
    } finally {
      clearTimeout(timeoutId);
    }
  };

  try {
    return await attemptFetch();
  } catch (error) {
    const message = error instanceof Error ? error.message : "";
    const shouldRetry =
      message.includes("[NETWORK_TIMEOUT]") || error instanceof TypeError;

    if (shouldRetry) {
      if (isDebugSupabase()) {
        console.warn("[SB_REQ_RETRY]", { reason: message || "TypeError" });
      }
      return attemptFetch();
    }
    throw error;
  }
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  global: {
    fetch: fetchWithTimeout,
  },
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    multiTab: false,
    // Mobile web often hangs on Navigator LockManager after tab/background resume.
    // Use a single-tab lock strategy to avoid lock timeout deadlocks.
    lock: async (_name, _acquireTimeout, fn) => await fn(),
  },
});
