// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error(
    "Missing Supabase environment variables. Please set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY."
  );
}

const fetchWithTimeout: typeof fetch = async (input, init) => {
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), 15000);

  try {
    return await fetch(input, {
      ...init,
      signal: controller.signal,
    });
  } finally {
    clearTimeout(timeout);
  }
};

const withTimeout = <T,>(promise: Promise<T>, timeoutMs: number): Promise<T> =>
  Promise.race([
    promise,
    new Promise<T>((_, reject) =>
      setTimeout(() => reject(new Error(`Supabase request timeout ${timeoutMs}ms`)), timeoutMs)
    ),
  ]);

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  global: {
    fetch: fetchWithTimeout,
  },
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    multiTab: false,
    lock: async (...args: unknown[]) => {
      const acquire = args[args.length - 1];
      if (typeof acquire === "function") {
        return await (acquire as () => Promise<unknown> | unknown)();
      }
      return null;
    },
  },
});

export async function restoreSupabaseSession() {
  const {
    data: { session },
    error: sessionError,
  } = await withTimeout(supabase.auth.getSession(), 10000);

  if (sessionError) {
    throw sessionError;
  }

  if (session && session.expires_at) {
    const expiresInMs = session.expires_at * 1000 - Date.now();
    if (expiresInMs < 60_000) {
      const { error: refreshError } = await withTimeout(supabase.auth.refreshSession(), 10000);
      if (refreshError) {
        throw refreshError;
      }
    }
  }

  return session;
}

export function reconnectSupabaseRealtime() {
  try {
    supabase.realtime.connect();
    const channels = supabase.getChannels();
    channels.forEach((channel) => {
      const state = (channel as { state?: string }).state;
      if (state === "closed") {
        channel.subscribe();
      }
    });
  } catch (error) {
    console.error("[SUPABASE_REALTIME_RECONNECT_ERROR]", error);
  }
}
